"""Create events

Revision ID: efc6d6c297a3
Revises: 
Create Date: 2025-11-10 15:41:27.866592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc6d6c297a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('HACKATHON', 'MEETUP', 'PARTY', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('submitor_email', sa.String(length=64), nullable=False),
    sa.Column('submitor_name', sa.String(length=64), nullable=False),
    sa.Column('location_text', sa.String(length=64), nullable=False),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    sa.Enum(name='eventtype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
